// <auto-generated />
using System;
using ArtistOS.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArtistOS.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtistOS.Api.Models.AnalyticsSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Comments")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.Property<long>("SubscribersGained")
                        .HasColumnType("bigint");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.Property<long>("WatchTimeMinutes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("SongId", "SnapshotDate");

                    b.HasIndex("SongId", "Platform", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("AnalyticsSnapshots");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.AudioAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("ExternalFileReferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExternalFileReferenceId");

                    b.HasIndex("SongId");

                    b.HasIndex("SongId", "Type");

                    b.ToTable("AudioAssets");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.ContentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Platform")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly?>("PublishedAt")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ScheduledAt")
                        .HasColumnType("date");

                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("SongId", "ScheduledAt");

                    b.HasIndex("SongId", "Status");

                    b.ToTable("ContentItems");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ContributorName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SplitPercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("SongId", "Role");

                    b.HasIndex("SongId", "Status");

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.ExternalFileReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("GoogleDriveConnectionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("boolean");

                    b.Property<int?>("LinkedResourceId")
                        .HasColumnType("integer");

                    b.Property<string>("LinkedResourceType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("SongId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebViewLink")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("GoogleDriveConnectionId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("SongId");

                    b.HasIndex("OwnerUserId", "Provider", "ExternalId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "Provider", "ResourceType", "SongId");

                    b.ToTable("ExternalFileReferences");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.GoogleDriveConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("GoogleEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GrantedScopes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LastSuccessfulRefreshAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProtectedRefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RootFolderId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "GoogleSubject");

                    b.ToTable("GoogleDriveConnections");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.Release", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Distributor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Isrc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Platforms")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("ReleaseType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Upc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SongId")
                        .IsUnique();

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.ReleaseChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("ReleaseId", "Key")
                        .IsUnique();

                    b.HasIndex("ReleaseId", "SortOrder");

                    b.ToTable("ReleaseChecklistItems");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.VisualAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExternalFileReferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExternalFileReferenceId");

                    b.HasIndex("SongId");

                    b.HasIndex("SongId", "Type");

                    b.ToTable("VisualAssets");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.AnalyticsSnapshot", b =>
                {
                    b.HasOne("ArtistOS.Api.Models.Song", "Song")
                        .WithMany("AnalyticsSnapshots")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.AudioAsset", b =>
                {
                    b.HasOne("ArtistOS.Api.Models.ExternalFileReference", "ExternalFileReference")
                        .WithMany()
                        .HasForeignKey("ExternalFileReferenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArtistOS.Api.Models.Song", "Song")
                        .WithMany("AudioAssets")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalFileReference");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.ContentItem", b =>
                {
                    b.HasOne("ArtistOS.Api.Models.Song", "Song")
                        .WithMany("ContentItems")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.Credit", b =>
                {
                    b.HasOne("ArtistOS.Api.Models.Song", "Song")
                        .WithMany("Credits")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.ExternalFileReference", b =>
                {
                    b.HasOne("ArtistOS.Api.Models.GoogleDriveConnection", "GoogleDriveConnection")
                        .WithMany("ExternalFileReferences")
                        .HasForeignKey("GoogleDriveConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArtistOS.Api.Models.User", "OwnerUser")
                        .WithMany("ExternalFileReferences")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtistOS.Api.Models.Song", "Song")
                        .WithMany("ExternalFileReferences")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GoogleDriveConnection");

                    b.Navigation("OwnerUser");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.GoogleDriveConnection", b =>
                {
                    b.HasOne("ArtistOS.Api.Models.User", "User")
                        .WithOne("GoogleDriveConnection")
                        .HasForeignKey("ArtistOS.Api.Models.GoogleDriveConnection", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.Release", b =>
                {
                    b.HasOne("ArtistOS.Api.Models.Song", "Song")
                        .WithOne("Release")
                        .HasForeignKey("ArtistOS.Api.Models.Release", "SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.ReleaseChecklistItem", b =>
                {
                    b.HasOne("ArtistOS.Api.Models.Release", "Release")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.Song", b =>
                {
                    b.HasOne("ArtistOS.Api.Models.User", "OwnerUser")
                        .WithMany("Songs")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.VisualAsset", b =>
                {
                    b.HasOne("ArtistOS.Api.Models.ExternalFileReference", "ExternalFileReference")
                        .WithMany()
                        .HasForeignKey("ExternalFileReferenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArtistOS.Api.Models.Song", "Song")
                        .WithMany("VisualAssets")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalFileReference");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.GoogleDriveConnection", b =>
                {
                    b.Navigation("ExternalFileReferences");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.Release", b =>
                {
                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.Song", b =>
                {
                    b.Navigation("AnalyticsSnapshots");

                    b.Navigation("AudioAssets");

                    b.Navigation("ContentItems");

                    b.Navigation("Credits");

                    b.Navigation("ExternalFileReferences");

                    b.Navigation("Release");

                    b.Navigation("VisualAssets");
                });

            modelBuilder.Entity("ArtistOS.Api.Models.User", b =>
                {
                    b.Navigation("ExternalFileReferences");

                    b.Navigation("GoogleDriveConnection");

                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
